# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd53b7f85085d89583fe02dbc0b1d993f6b7dcdc36881a1baad690a5e143eb2e290505b2584d54df7383aee7245d7af19e7402ad901d1b13a187ca7ab1ba35c3

test:
  secret_key_base: fd35f3ffbcca8949cc4c5247925af783f64ee3dd06f36ffad5844f865b096b9bea6c0c17e14d96109e12e80dc5826da2b39289c3def19f363102e25e1d3a61e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
